<?php
namespace ah;

require_once dirname(__FILE__).'/../init.php';

/**
 * Test class for Autoloader.
 * Generated by PHPUnit on 2011-05-05 at 22:16:29.
 */
class AutoloaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Autoloader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Autoloader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testRegister()
    {
        // through
    }

    public function testAhLoad()
    {
        $this->assertTrue($this->object->ahLoad('ah\Cache'));

        $this->assertFalse($this->object->ahLoad('ah\isNotExists'));
    }

    public function testAhAppLoad()
    {
        $this->assertTrue($this->object->ahAppLoad('app\action\Index'));

        $this->assertFalse($this->object->ahAppLoad('ah\action\Index'));
    }

    public function testAhCoreLoad()
    {
        $this->assertTrue($this->object->ahCoreLoad('ah\Config'));

        $this->assertFalse($this->object->ahCoreLoad('app\Config'));
    }

    public function testAhCommonLoad()
    {
        $this->assertTrue($this->object->ahCommonLoad('Template'));
        $this->assertTrue($this->object->ahCommonLoad('HTTP_Client'));

        $this->assertFalse($this->object->ahCommonLoad('HTTP\Dummy'));
    }

    public function testSfLoad()
    {
        $this->assertTrue($this->object->sfLoad('sfEvent'));

        $this->assertFalse($this->object->sfLoad('sfDummy'));
    }

    public function testTerminate()
    {
        try {
            class_exists('ah\isnot\exists');
        } catch ( \Exception $e ) {
            return;
        }

        $this->fail('Exception not Returned.');
    }
}
?>
